"""add columns for images urls

Revision ID: e59a9581299f
Revises: c18ed555b678
Create Date: 2026-09-24 23:21:29.352545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e59a9581299f'
down_revision: Union[str, Sequence[str], None] = 'c18ed555b678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Additional_items', sa.Column('image_front_url', sa.String(length=512), nullable=True))
    op.add_column('Additional_items', sa.Column('image_back_url', sa.String(length=512), nullable=True))
    op.add_column('Filter_items', sa.Column('image_front_url', sa.String(length=512), nullable=True))
    op.add_column('Filter_items', sa.Column('image_back_url', sa.String(length=512), nullable=True))
    op.add_column('oil_engine_items', sa.Column('image_front_url', sa.String(length=512), nullable=True))
    op.add_column('oil_engine_items', sa.Column('image_back_url', sa.String(length=512), nullable=True))
    op.add_column('transmission_oil_items', sa.Column('image_front_url', sa.String(length=512), nullable=True))
    op.add_column('transmission_oil_items', sa.Column('image_back_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transmission_oil_items', 'image_back_url')
    op.drop_column('transmission_oil_items', 'image_front_url')
    op.drop_column('oil_engine_items', 'image_back_url')
    op.drop_column('oil_engine_items', 'image_front_url')
    op.drop_column('Filter_items', 'image_back_url')
    op.drop_column('Filter_items', 'image_front_url')
    op.drop_column('Additional_items', 'image_back_url')
    op.drop_column('Additional_items', 'image_front_url')
    # ### end Alembic commands ###
